### ISSUE TITLE
research_template.html is missing

### ISSUE THREAD

**Issue by PhilipNZ** [Saidiibrahim/langgraph-cookbook#1]
Thanks a lot for sharing your ideas and code on building agentic systems. However, when I run in newsletter-cron, I got 

/newsletter-cron$ python3   main.py 

Traceback (most recent call last):
  File "/git_repositories/InformationBottleneck/ib/lib/python3.12/site-packages/storage3/_sync/file_api.py", line 47, in _request
    response.raise_for_status()
  File "/git_repositories/InformationBottleneck/ib/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://xxkshbekwgsblghfahda.supabase.co/storage/v1/object/test/research_template.html'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/git_repositories/langgraph-cookbook/apps/newsletter-cron/main.py", line 7, in <module>
    from graph import graph
  File "/git_repositories/langgraph-cookbook/apps/newsletter-cron/graph.py", line 5, in <module>
    from tools import load_html_template, EmailSender, search, get_contents, find_similar
  File "/git_repositories/langgraph-cookbook/tools/__init__.py", line 1, in <module>
    from .html_loader import load_html_template
  File "/git_repositories/langgraph-cookbook/tools/html_loader.py", line 12, in <module>
    html_template = read_file(
                    ^^^^^^^^^^
  File "/git_repositories/langgraph-cookbook/utils/file_utils.py", line 16, in read_file
    res = supabase.storage.from_(bucket_name).download(file_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git_repositories/InformationBottleneck/ib/lib/python3.12/site-packages/storage3/_sync/file_api.py", line 342, in download
    response = self._request(
               ^^^^^^^^^^^^^^
  File "/git_repositories/InformationBottleneck/ib/lib/python3.12/site-packages/storage3/_sync/file_api.py", line 51, in _request
    raise StorageException({**resp, "statusCode": response.status_code})
storage3.utils.StorageException: {'statusCode': 400, 'error': 'not_found', 'message': 'Object not found'}

It looks like research_template.html is missing. I can find only newsletter_template.html in folder ./config/. Do you mind sharing research_template.html ?

Thanks a lot!

**Comment by Saidiibrahim** [comment]
Hi Phillip. I've added the missing research template to the config directory.

You're welcome to submit changes to the repo 🙏🏾
